# version: '3.7'

services:
  currency-exchange:
    image: masterpece/currency-exchange:1.0
    mem_limit: 700m
    ports:
      - "8000:8001"
    networks:
      - currency-network
    depends_on: 
      - naming-server
      - openzipkin

  naming-server:
    image: masterpece/eureka-naming-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  openzipkin:
    image: openzipkin/zipkin:latest
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - currency-network

  currency-conversion:
    image: masterpece/cunrrency-conversion:1.0
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on: 
      - naming-server
      - openzipkin

networks:
  currency-network:
